theme: jekyll-theme-minimal
title: CoderDojo Bratislava
description: Stránka klubu CoderDojo Bratislava
plugins:
  - jekyll-seo-tag
  
#seo
url: https://bratislava.coderdojo.sk/
links:
 -https://www.facebook.com/CoderDojoBratislava
lang: sk
google_site_verification: HjwehqBFnFUdY4dtEqr3UJsRi9H6lJinEIdifO2IU_s
