theme: jekyll-theme-minimal
title: CoderDojo Bratislava
description: Bezplatný klub programovania pre deti od 7 do 17 rokov
plugins:
  - jekyll-seo-tag
  
#seo
lang: sk
url: https://bratislava.coderdojo.sk
social: 
  name: CoderDojo Bratislava
  links:
    - https://www.facebook.com/CoderDojoBratislava
google_site_verification: HjwehqBFnFUdY4dtEqr3UJsRi9H6lJinEIdifO2IU_s
